references:
  defaults: &defaults
    working_directory: ~/bigtest
    docker:
      - image: circleci/node:8

  cache_key: &cache_key
    bigtest-{{ .Branch }}-{{ checksum "yarn.lock" }}

  restore_cache: &restore_cache
    restore_cache:
      name: Restore cache
      key: *cache_key

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/bigtest

version: 2.0
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules
            # globs don't work for save_cache :(
            - packages/convergence/node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Build packages
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: packages/**/dist

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *attach_workspace
      - run:
          name: Run tests
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *attach_workspace
      - run:
          name: Setup NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: ./bin/each-pkg --newer npm publish -- --access=public
      - run:
          name: Push Tags
          command: git push --tags

workflows:
  version: 2
  default:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
