on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Tests
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install XVFB
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - name: Install dependencies
        run: yarn
      - name: Prepackage
        run: yarn prepack
      - name: Run tests
        run: xvfb-run --auto-servernum -- yarn test --browsers=ChromeHeadless
